name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: install dependencies
      run: npm ci

    - name: build
      run: npm run build

    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      run: npm run release
